//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoneySheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptId { get; set; }
        public int InvoiceId { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public decimal ReceiptAmount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
